/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Alquiler;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author antho
 */
public class PanelAlquileres extends javax.swing.JPanel {

    DefaultTableModel modelo;
    String item;
    String tipoBusqueda;

    public PanelAlquileres() {
        initComponents();
        popupMenu.add(subMenu);
        item = "Registradas";
        tipoBusqueda = "Solicitudes";
        String[] titulos = {"Fecha", "Cedula", "Dias", "Cant. Pasajeros", "Marca", "Modelo", "Extras", "Categoria", "Estado"};
        modelo = new DefaultTableModel(null, titulos);
        tablaSolicitudes.setModel(modelo);
        Queue.llenarTabla("LlenarSolicitudes", modelo);
        btnAsignarVehiculo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        subMenu = new javax.swing.JPanel();
        btnCambiarEstado = new javax.swing.JButton();
        txtOculta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        btnSolicitud = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAsignarVehiculo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();

        subMenu.setBackground(new java.awt.Color(204, 102, 0));

        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subMenuLayout = new javax.swing.GroupLayout(subMenu);
        subMenu.setLayout(subMenuLayout);
        subMenuLayout.setHorizontalGroup(
            subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCambiarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subMenuLayout.setVerticalGroup(
            subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCambiarEstado)
        );

        setBackground(new java.awt.Color(204, 102, 0));
        setPreferredSize(new java.awt.Dimension(696, 500));

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaSolicitudes.setComponentPopupMenu(popupMenu);
        tablaSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitudes);

        btnSolicitud.setText("Nueva solicitud");
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAsignarVehiculo.setText("Asignar Vehiculo");
        btnAsignarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarVehiculoActionPerformed(evt);
            }
        });

        text.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jScrollPane2.setViewportView(text);

        label2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        label2.setText("Datos de solicitud");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Control de Alquileres");

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registradas", "Rechazadas", "Registro de solicitudes" }));
        combox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSolicitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefrescar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsignarVehiculo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarVehiculo)
                    .addComponent(btnSolicitud)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRefrescar)
                    .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudesMouseClicked
        if (evt.getClickCount() == 1) {

            JTable receptor = (JTable) evt.getSource();
            if (receptor.getColumnCount() == 9) {
                if (item.equalsIgnoreCase("Registradas")) {
                    String datos = "Fecha: " + receptor.getValueAt(receptor.getSelectedRow(), 0).toString() + "\nCédula: " + receptor.getValueAt(receptor.getSelectedRow(), 1).toString()
                            + "\nDias: " + receptor.getValueAt(receptor.getSelectedRow(), 2).toString() + "\nCant. Pasajeros: " + receptor.getValueAt(receptor.getSelectedRow(), 3).toString()
                            + " \nMarca: " + receptor.getValueAt(receptor.getSelectedRow(), 4).toString() + "\nModelo: " + receptor.getValueAt(receptor.getSelectedRow(), 5).toString()
                            + "\nExtras: " + receptor.getValueAt(receptor.getSelectedRow(), 6).toString() + "\nCategoria: " + receptor.getValueAt(receptor.getSelectedRow(), 7).toString()
                            + "\nEstado: " + receptor.getValueAt(receptor.getSelectedRow(), 8).toString();
                    txtOculta.setText(receptor.getValueAt(receptor.getSelectedRow(), 1).toString());
                    text.setText(datos);
                    btnAsignarVehiculo.setEnabled(true);
                    if (receptor.getValueAt(receptor.getSelectedRow(), 8).toString().equalsIgnoreCase("Registrada")) {
                        btnCambiarEstado.setText("Rechazar solicitud");
                        btnCambiarEstado.setEnabled(true);
                    }
                } else if (item.equalsIgnoreCase("Rechazadas")) {
                    String datos = "Fecha: " + receptor.getValueAt(receptor.getSelectedRow(), 0).toString() + "\nCédula: " + receptor.getValueAt(receptor.getSelectedRow(), 1).toString()
                            + "\nDias: " + receptor.getValueAt(receptor.getSelectedRow(), 2).toString() + "\nCant. Pasajeros: " + receptor.getValueAt(receptor.getSelectedRow(), 3).toString()
                            + " \nMarca: " + receptor.getValueAt(receptor.getSelectedRow(), 4).toString() + "\nModelo: " + receptor.getValueAt(receptor.getSelectedRow(), 5).toString()
                            + "\nExtras: " + receptor.getValueAt(receptor.getSelectedRow(), 6).toString() + "\nCategoria: " + receptor.getValueAt(receptor.getSelectedRow(), 7).toString()
                            + "\nEstado: " + receptor.getValueAt(receptor.getSelectedRow(), 8).toString();
                    txtOculta.setText(receptor.getValueAt(receptor.getSelectedRow(), 1).toString());
                    text.setText(datos);
                    btnAsignarVehiculo.setEnabled(false);
                    if (receptor.getValueAt(receptor.getSelectedRow(), 8).toString().equalsIgnoreCase("Rechazada")) {
                        btnCambiarEstado.setText("Agregar a solicitudes");
                        btnCambiarEstado.setEnabled(true);
                    }
                }

            } else if (receptor.getColumnCount() == 7) {
                String datos = "Fecha: " + receptor.getValueAt(receptor.getSelectedRow(), 0).toString() + "\nCedula: " + receptor.getValueAt(receptor.getSelectedRow(), 1).toString()
                        + "\nDias: " + receptor.getValueAt(receptor.getSelectedRow(), 2).toString() + "\nPlaca: " + receptor.getValueAt(receptor.getSelectedRow(), 3).toString()
                        + "\nPrecio total: " + receptor.getValueAt(receptor.getSelectedRow(), 4).toString() + " \nCategoria: " + receptor.getValueAt(receptor.getSelectedRow(), 5).toString()
                        + "\nEstado: " + receptor.getValueAt(receptor.getSelectedRow(), 6).toString();
                txtOculta.setText(receptor.getValueAt(receptor.getSelectedRow(), 1).toString());
                text.setText(datos);
                btnAsignarVehiculo.setEnabled(false);
                if (receptor.getValueAt(receptor.getSelectedRow(), 6).toString().equalsIgnoreCase("Procesada")) {
                    btnCambiarEstado.setText("Finalizar");
                    btnCambiarEstado.setEnabled(true);
                } else if (receptor.getValueAt(receptor.getSelectedRow(), 6).toString().equalsIgnoreCase("Finalizada")) {
                    btnCambiarEstado.setText("Finalizar");
                    btnCambiarEstado.setEnabled(false);
                }
            }

        }
    }//GEN-LAST:event_tablaSolicitudesMouseClicked

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        AgregarSolicitud a = new AgregarSolicitud();
        a.setVisible(true);
    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        refrescar();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Queue.buscar(tipoBusqueda, txtBuscar.getText(), modelo);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        Queue.cambiarEstado(txtOculta.getText());
        Queue.llenarTabla("LlenarSolicitudes", modelo);
        refrescar();
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void comboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxItemStateChanged
        if (combox.getSelectedItem().equals("Registradas")) {
            tipoBusqueda = "Solicitudes";
            text.setText("");
            String[] titulos = {"Fecha", "Cedula", "Dias", "Cant. Pasajeros", "Marca", "Modelo", "Extras", "Categoria", "Estado"};
            modelo = new DefaultTableModel(null, titulos);
            tablaSolicitudes.setModel(modelo);
            Queue.llenarTabla("LlenarSolicitudes", modelo);
            item = "Registradas";
        } else if (combox.getSelectedItem().equals("Rechazadas")) {
            txtBuscar.setText("");
            tipoBusqueda = "Solicitudes";
            text.setText("");
            btnAsignarVehiculo.setEnabled(false);
            String[] titulos = {"Fecha", "Cedula", "Dias", "Cant. Pasajeros", "Marca", "Modelo", "Extras", "Categoria", "Estado"};
            modelo = new DefaultTableModel(null, titulos);
            tablaSolicitudes.setModel(modelo);
            Queue.llenarTabla("LlenarRechazadas", modelo);
            item = "Rechazadas";

        } else if (combox.getSelectedItem().equals("Registro de solicitudes")) {
            txtBuscar.setText("");
            tipoBusqueda = "Registradas";
            text.setText("");
            btnAsignarVehiculo.setEnabled(false);
            String[] titulos = {"Fecha", "Cedula", "Dias", "Placa", "Precio total", "Categoria", "Estado"};
            modelo = new DefaultTableModel(null, titulos);
            tablaSolicitudes.setModel(modelo);
            Queue.llenarTabla("LlenarRegistro", modelo);
        }

    }//GEN-LAST:event_comboxItemStateChanged

    private void btnAsignarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarVehiculoActionPerformed
        AsignarVehiculo aV = new AsignarVehiculo();
        aV.txtCed.setText(txtOculta.getText());
        aV.setVisible(true);
    }//GEN-LAST:event_btnAsignarVehiculoActionPerformed

    private void refrescar() {
        tipoBusqueda = "Solicitudes";
        text.setText("");
        txtBuscar.setText("");
        item = "Registradas";
        combox.setSelectedIndex(0);
        btnCambiarEstado.setText("Rechazar solicitud");
        Queue.llenarTabla("LlenarSolicitudes", modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarVehiculo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label2;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JPanel subMenu;
    private javax.swing.JTable tablaSolicitudes;
    private javax.swing.JTextPane text;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtOculta;
    // End of variables declaration//GEN-END:variables
}
